name: Build Gamemode (Windows Runner)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Gamemode using Custom Action
        uses: devbluen/openmp-build-action@v2
        with:
          gamemode_name: 'main'
          core_libs: 'amxsscanf libmariadb log-core'
          extra_data_folders: 'scriptfiles/database'

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: deploy_win/

      - name: Upload Linux Standard Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-standard
          path: deploy_linux/

      - name: Upload Linux Dynamic Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-dynamic
          path: deploy_linux_dyn/